### PR TITLE
refactor: tooltip

### PR DESCRIPTION
**Pull request by kaitmore**
- refactor Tooltip to use hooks
- add new react-popper peer dep (@popperjs/core)
- add `popperOptions` to pass through props to popper https://popper.js.org/docs/v2/constructors/#options
- add more options to `position` https://popper.js.org/docs/v2/constructors/#placement

To test:
- view in storybook
- test in dashboard

### CODE REVIEW

**Comment by tilleryd** [comment]
Please add `react-popper` as a 5th peer dependency to https://github.com/greymatter-io/gm-ui-components#installation

**Comment by tilleryd** [comment]
Please also add react-popper to package.json `peerDependencies` list.

**Comment by kaitmore** [comment]
@tilleryd ya know I was just thinking about that too... how has this been working in the dashboard when it's always been a devDependency? 🤔

**Comment by tilleryd** [comment]
Dev dependencies work fine in storybook. You still need to install peers in the consuming app.

**Review by tilleryd — APPROVED** [review]
tested and approved

**Pull request merged**
