### PR TITLE
fix: Changed alt text and copyright to from Decipher to greymatter.io Inc.

### PR DESCRIPTION
**Pull request by mdversion01**
[sc-18390] Changed alt text and copyright to from Decipher to greymatter.io Inc. Updated greymatter logo.

image

### CODE REVIEW

**Comment by tilleryd** [comment]
This would be a good time to update the footer logo to the latest.

**Comment by tilleryd** [comment]
I ran Storybook and visually verified the update.

**Comment by mdversion01** [comment]
@tilleryd what's up with the ci checks? They've been like that since last week.

**Comment by tilleryd** [comment]
@mdversion01 We just need to migrate this repo to Buildkite. I ran through the verification steps locally. Before we release, I'll be sure to get this repo in Buildkite.

**Pull request merged**
