### PR TITLE
refactor: retire spacingScale in favor of rem units

### PR DESCRIPTION
**Pull request by shanberg**
All components should be identical. `spacingScale(1)` = `1rem`. Easier to use, and removes the unnecessary abstraction, as well as providing cleaner output.

- Replace all uses of `spacingScale` with equal size CSS rem unit.
- Update documentation to recommend rem units.
- Console warning to indicate deprecation of `spacingScale`.

### CODE REVIEW

**Comment by tilleryd** [comment]
I see less rounded corners of components and I'm ok with that. Was it intentional?

Left side is master, right side is this branch:
Screen Shot 2020-07-23 at 4 40 24 PM

**Comment by tilleryd** [comment]
@shanberg I like that you've deprecated spacingScale rather than an outright replacement. 🎉

**Comment by shanberg** [comment]
> I see more rounded corners of components. I actually prefer the way it was. Was it intentional?

@tilleryd Unintentional

**Comment by shanberg** [comment]
We found issues in the dashboard with some components seemingly getting an incorrect SPACING_SCALE value. I'll have to investigate further.

**Comment by dontlaugh** [comment]
@shanberg This has been open for a long time. Can you convert this to an issue, leave the branch up (if you think that's right), and link to the branch in the issue?

If an existing issue exists that's appropriate, summarize there.

**Pull request closed without merging**
